# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool: default

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    version: '5.0.x'
    includePreviewVersions: true # Required for preview versions

- task: UseDotNet@2
  inputs:
    version: '3.0.x'
    packageType: runtime

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    workingDirectory: ./Booking.Server
displayName: restore

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    arguments: '--no-restore --output artifacts'
    workingDirectory: ./Booking.Server
  displayName: 'dotnet build --no-restore --output artifacts'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    arguments: '--no-restore --no-build'
    workingDirectory: ./Booking.Server
  displayName: 'dotnet build --no-restore --output artifacts'

#- script: |
#    dotnet restore
#    dotnet publish --no-restore --output artifacts
#    dotnet test --no-restore --no-build
#  workingDirectory: ./Booking.Server
#  displayName: 'dotnet restore, build and test'

- script: ls -R

- publish: ./Booking.Server/artifacts
