# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    version: '6.0.x'
    includePreviewVersions: true # Required for preview versions

- script: dotnet restore
  workingDirectory: ./Booking.Server
  displayName: restore

- script: 'dotnet publish --no-restore --output artifacts'
  workingDirectory: ./Booking.Server
  displayName: 'dotnet build --no-restore --output artifacts'

- script: 'dotnet test --no-restore --no-build'
  workingDirectory: ./Booking.Server
  displayName: 'dotnet build --no-restore --output artifacts'

- publish: ./Booking.Server/artifacts
